### ISSUE TITLE
Usprawnienie profilu użytkownika

### ISSUE THREAD

**Issue by Kethableez** [Kethableez/AnyTravel#58]
Poprawić wygląd, dodać obsługę wyświetlania zdjęcia profilowego, wyświetlać narazie podstawowe dane uzytkownika:
Imię, nazwisko, avatar, kontrolki odpowiadające za edycję i usuwanie konta

Postarać się o nietrywialny wygląd który wpasowuje się w tematykę reszty aplikacji
https://bulma.io/documentation/

**Comment by Kethableez** [comment]
Poprawić wygląd, dodać obsługę wyświetlania zdjęcia profilowego, wyświetlać narazie podstawowe dane uzytkownika:
Imię, nazwisko, avatar, kontrolki odpowiadające za edycję i usuwanie konta

Postarać się o nietrywialny wygląd który wpasowuje się w tematykę reszty aplikacji
https://bulma.io/documentation/

**Comment by xoMichal** [comment]
[http://localhost:9000/api/file/download/avatar/default.png](http://localhost:9000/api/file/download/avatar/default.png?fbclid=IwAR3vwDPY09rBClGmHD1IAFUzRoZgVGySoz2aNAC-PTkJ_qK0R3rfRDtpGlg)

[https://angular.io/guide/inputs-outputs](https://angular.io/guide/inputs-outputs?fbclid=IwAR03D__UGXApo3Yq-hrwq69yM1uBRzU8GY2qM_gaEHemvi3LVZlZa1B_fkY)

**Comment by xoMichal** [comment]
main-page/pages/attraction/components/attraction-card/attraction-card.compoent    ścieżka z ściągą do pliku z tworzeniem ścieżkia awatara

**Comment by xoMichal** [comment]
Rozbić edit data na edit data i change password(do tego zrobić nowy formularz)
dodać funkcję anulowania formularza
dodać funkcję wypełnienia formularza edycji danych aktualnymi danymi
za pomocą css zrobić powiększanie zdj profilowego
